# Generated by Django 4.2.20 on 2025-08-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
