# Generated by Django 4.2.20 on 2025-08-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_remove_invoice_paid_date_invoice_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
