# Generated by Django 4.2.20 on 2025-08-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_invoice_paid_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_year',
        ),
    ]
