# Generated by Django 4.2.20 on 2025-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_alter_event_options_alter_event_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='money_trans_invoice_aa6611_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Optional', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice_number'], name='money_trans_invoice_d1f344_idx'),
        ),
    ]
