# Generated by Django 4.2.20 on 2025-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_remove_transaction_money_trans_invoice_aa6611_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='schedule_c_line',
            field=models.CharField(blank=True, help_text='Enter Schedule C line number.', max_length=10, null=True),
        ),
    ]
