# Generated by Django 4.2.20 on 2025-08-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_subcategory_schedule_c_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miles',
            name='invoice',
        ),
        migrations.AddField(
            model_name='miles',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
