# Generated by Django 4.2.20 on 2025-08-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_remove_miles_invoice_miles_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='miles',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.event'),
        ),
    ]
