# Generated by Django 4.2.20 on 2025-08-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_miles_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miles',
            name='job',
        ),
    ]
