# Generated by Django 4.2.20 on 2025-08-07 03:11

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to=app.models.license_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_completed', models.DateField()),
                ('required', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=app.models.training_certificate_upload_path)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='app.pilotprofile')),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
    ]
