# Generated by Django 4.2.20 on 2025-08-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-active', 'equipment_type', 'name'], 'verbose_name_plural': 'Equipment'},
        ),
    ]
